const  pickupLines = [
    "Are you a campfire? Because you're hot and I want s'more.",
    "Do you have a name, or can I call you mine?",
    "Are you a Wi-Fi signal? Because I'm feeling a connection.",
    "Are you a bank loan? Because you have my interest.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Are you a magician? Whenever I look at you, everyone else disappears.",
    "Is your name Google? Because you have everything I've been searching for.",
    "Is your name Chapstick? Because you're da balm!",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you a camera? Every time I look at you, I smile.",
    "Do you have a pencil? Because I want to erase your past and write our future.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "Is your name Wi-Fi? Because I'm really feeling a connection.",
    "Do you have a sunburn, or are you always this hot?",
    "Do you have a map? I just got lost in your eyes.",
    "If you were a fruit, you'd be a fineapple.",
    "I must be a snowflake, because I've fallen for you.",
    "Is your name Waldo? Because someone like you is hard to find.",
    "I must be a snowflake, because I've fallen for you.",
    "Do you have a name, or can I call you mine?",
    "Are you a Wi-Fi signal? Because I'm feeling a connection.",
    "Are you a bank loan? Because you have my interest.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Are you a magician? Whenever I look at you, everyone else disappears.",
    "Is your name Google? Because you have everything I've been searching for.",
    "Is your name Chapstick? Because you're da balm!",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you a camera? Every time I look at you, I smile.",
    "Do you have a pencil? Because I want to erase your past and write our future.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "Is your name Wi-Fi? Because I'm really feeling a connection.",
    "Do you have a sunburn, or are you always this hot?",
    "Do you have a map? I just got lost in your eyes.",
    "If you were a fruit, you'd be a fineapple.",
    "I must be a snowflake, because I've fallen for you.",
    "Is your name Waldo? Because someone like you is hard to find.",
    "I must be a snowflake, because I've fallen for you.",
    "Do you have a name, or can I call you mine?",
    "Are you a Wi-Fi signal? Because I'm feeling a connection.",
    "Are you a bank loan? Because you have my interest.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Are you a magician? Whenever I look at you, everyone else disappears.",
    "Is your name Google? Because you have everything I've been searching for.",
    "Is your name Chapstick? Because you're da balm!",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you a camera? Every time I look at you, I smile.",
    "Do you have a pencil? Because I want to erase your past and write our future.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "Is your name Wi-Fi? Because I'm really feeling a connection.",
    "Do you have a sunburn, or are you always this hot?",
    "Do you have a map? I just got lost in your eyes.",
    "If you were a fruit, you'd be a fineapple.",
    "I must be a snowflake, because I've fallen for you.",
    "Is your name Waldo? Because someone like you is hard to find.",
    "I must be a snowflake, because I've fallen for you.",
    "Do you have a name, or can I call you mine?",
    "Are you a Wi-Fi signal? Because I'm feeling a connection.",
    "Are you a bank loan? Because you have my interest.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Are you a magician? Whenever I look at you, everyone else disappears.",
    "Is your name Google? Because you have everything I've been searching for.",
    "Is your name Chapstick? Because you're da balm!",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you a camera? Every time I look at you, I smile.",
    "Do you have a pencil? Because I want to erase your past and write our future.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "Is your name Wi-Fi? Because I'm really feeling a connection.",
    "Do you have a sunburn, or are you always this hot?",
    "Do you have a map? I just got lost in your eyes.",
    "If you were a fruit, you'd be a fineapple.",
    "I must be a snowflake, because I've fallen for you.",
    "Is your name Waldo? Because someone like you is hard to find.",
    "I must be a snowflake, because I've fallen for you.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "Is your name Wi-Fi? Because I'm really feeling a connection.",
    "Do you have a sunburn, or are you always this hot?",
    "Do you have a map? I just got lost in your eyes.",
    "If you were a fruit, you'd be a fineapple.",
    "I must be a snowflake, because I've fallen for you.",
    "Is your name Waldo? Because someone like you is hard to find."
  ];

  module.exports = pickupLines
  